<?php



function deleteThisFile($nameOfFile=false) {
	// 11-09-06 - this is being called by deleteForms which is called by deleteThisDatabaseTable
	// which is called in loopArray which is called in deleteTable when a table is being deleted.
	// The whole process starts on this page: 
	//
	// http://craigbuilders.cat4dev.com/authorized/scaffolding/index.php?formName=deleteTableForm.htm
	//
	// Basically, when we are in the scaffolding folder and we create a new database table, 7 forms/pages
	// are autogenerated. So when we delete a table, we want to delete those forms/pages as well. 

	global $controller; 
	
		$pathToSiteSpecificFiles = $controller->getVar("pathToSiteSpecificFiles"); 


	if ($nameOfFile) {
		$isDeleted = false; 
	
		if (file_exists($nameOfFile)) {
			$isDeleted = unlink($nameOfFile);
		} elseif (file_exists($pathToSiteSpecificFiles.$nameOfFile)) {
			$isDeleted = unlink($nameOfFile);
		} else {
			$controller->error("In deleteThisFile, we were unable to find the file '$nameOfFile'."); 
		}
	
		if (!$isDeleted) $controller->error("In deleteThisFile we were unable to delete the file '$nameOfFile'."); 
		return $isDeleted;
	} else {
		$controller->error("In deleteThisFile, we expected to be told the name of a file to delete, but we were not given a file name."); 
	}
}



?>	